name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ordinal-thinker-462919-t5
  REGION: europe-west1
  SERVICE_NAME: hotel-scope-app
  IMAGE: gcr.io/ordinal-thinker-462919-t5/hotel-scope
  CLOUDSQL_INSTANCE: ordinal-thinker-462919-t5:europe-west1:savvy-server

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t $IMAGE .

      - name: Push Docker image
        run: |
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --memory 16Gi \
            --cpu 8 \
            --concurrency 2 \
            --max-instances 10 \
            --add-cloudsql-instances $CLOUDSQL_INSTANCE \
            --env-vars-file env.yaml
