name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      #Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

            #Generar el archivo .env para el frontend
      - name: Generate .env for frontend
        run: |
          cp .env.production.example .env

      #Configurar autenticación en Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      #Configurar Google Cloud SDK (con autenticación correcta)
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      #Instalar dependencias
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm run build

      #Desplegar a Google App Engine
      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet

# TEST5